// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status_StatusCode int32

const (
	Status_FAILED          Status_StatusCode = 0
	Status_NO_IMPL_YET     Status_StatusCode = 1
	Status_INVALID_QUERY   Status_StatusCode = 2
	Status_PARTIAL_SUCCESS Status_StatusCode = 3
	Status_SUCCESS         Status_StatusCode = 4
	Status_READMSG         Status_StatusCode = 5
)

var Status_StatusCode_name = map[int32]string{
	0: "FAILED",
	1: "NO_IMPL_YET",
	2: "INVALID_QUERY",
	3: "PARTIAL_SUCCESS",
	4: "SUCCESS",
	5: "READMSG",
}

var Status_StatusCode_value = map[string]int32{
	"FAILED":          0,
	"NO_IMPL_YET":     1,
	"INVALID_QUERY":   2,
	"PARTIAL_SUCCESS": 3,
	"SUCCESS":         4,
	"READMSG":         5,
}

func (x Status_StatusCode) String() string {
	return proto.EnumName(Status_StatusCode_name, int32(x))
}

func (Status_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8, 0}
}

type Name struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Name) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Name                 *Name    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

type CreateReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (m *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(m, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchAgeReq struct {
	AgeRange             *SearchAgeReq_AgeRange `protobuf:"bytes,1,opt,name=ageRange,proto3" json:"ageRange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SearchAgeReq) Reset()         { *m = SearchAgeReq{} }
func (m *SearchAgeReq) String() string { return proto.CompactTextString(m) }
func (*SearchAgeReq) ProtoMessage()    {}
func (*SearchAgeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *SearchAgeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgeReq.Unmarshal(m, b)
}
func (m *SearchAgeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgeReq.Marshal(b, m, deterministic)
}
func (m *SearchAgeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgeReq.Merge(m, src)
}
func (m *SearchAgeReq) XXX_Size() int {
	return xxx_messageInfo_SearchAgeReq.Size(m)
}
func (m *SearchAgeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgeReq proto.InternalMessageInfo

func (m *SearchAgeReq) GetAgeRange() *SearchAgeReq_AgeRange {
	if m != nil {
		return m.AgeRange
	}
	return nil
}

type SearchAgeReq_AgeRange struct {
	From                 int32    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	ToIncluded           int32    `protobuf:"varint,2,opt,name=to_included,json=toIncluded,proto3" json:"to_included,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgeReq_AgeRange) Reset()         { *m = SearchAgeReq_AgeRange{} }
func (m *SearchAgeReq_AgeRange) String() string { return proto.CompactTextString(m) }
func (*SearchAgeReq_AgeRange) ProtoMessage()    {}
func (*SearchAgeReq_AgeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5, 0}
}

func (m *SearchAgeReq_AgeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgeReq_AgeRange.Unmarshal(m, b)
}
func (m *SearchAgeReq_AgeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgeReq_AgeRange.Marshal(b, m, deterministic)
}
func (m *SearchAgeReq_AgeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgeReq_AgeRange.Merge(m, src)
}
func (m *SearchAgeReq_AgeRange) XXX_Size() int {
	return xxx_messageInfo_SearchAgeReq_AgeRange.Size(m)
}
func (m *SearchAgeReq_AgeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgeReq_AgeRange.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgeReq_AgeRange proto.InternalMessageInfo

func (m *SearchAgeReq_AgeRange) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchAgeReq_AgeRange) GetToIncluded() int32 {
	if m != nil {
		return m.ToIncluded
	}
	return 0
}

type SearchNameReq struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchNameReq) Reset()         { *m = SearchNameReq{} }
func (m *SearchNameReq) String() string { return proto.CompactTextString(m) }
func (*SearchNameReq) ProtoMessage()    {}
func (*SearchNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *SearchNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchNameReq.Unmarshal(m, b)
}
func (m *SearchNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchNameReq.Marshal(b, m, deterministic)
}
func (m *SearchNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchNameReq.Merge(m, src)
}
func (m *SearchNameReq) XXX_Size() int {
	return xxx_messageInfo_SearchNameReq.Size(m)
}
func (m *SearchNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchNameReq proto.InternalMessageInfo

func (m *SearchNameReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResp) Reset()         { *m = SearchResp{} }
func (m *SearchResp) String() string { return proto.CompactTextString(m) }
func (*SearchResp) ProtoMessage()    {}
func (*SearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *SearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResp.Unmarshal(m, b)
}
func (m *SearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResp.Marshal(b, m, deterministic)
}
func (m *SearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResp.Merge(m, src)
}
func (m *SearchResp) XXX_Size() int {
	return xxx_messageInfo_SearchResp.Size(m)
}
func (m *SearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResp proto.InternalMessageInfo

func (m *SearchResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// A status message that is included to each response.
type Status struct {
	Code                 Status_StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=user.Status_StatusCode" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() Status_StatusCode {
	if m != nil {
		return m.Code
	}
	return Status_FAILED
}

func (m *Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("user.Status_StatusCode", Status_StatusCode_name, Status_StatusCode_value)
	proto.RegisterType((*Name)(nil), "user.Name")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*ListReq)(nil), "user.ListReq")
	proto.RegisterType((*CreateReq)(nil), "user.CreateReq")
	proto.RegisterType((*CreateResp)(nil), "user.CreateResp")
	proto.RegisterType((*SearchAgeReq)(nil), "user.SearchAgeReq")
	proto.RegisterType((*SearchAgeReq_AgeRange)(nil), "user.SearchAgeReq.AgeRange")
	proto.RegisterType((*SearchNameReq)(nil), "user.SearchNameReq")
	proto.RegisterType((*SearchResp)(nil), "user.SearchResp")
	proto.RegisterType((*Status)(nil), "user.Status")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x8e, 0xed, 0x36, 0x93, 0xb6, 0x31, 0x53, 0x24, 0xac, 0x22, 0x41, 0x64, 0x81, 0xa8,
	0x14, 0x29, 0x82, 0xf4, 0xc0, 0x11, 0x59, 0x49, 0x40, 0x96, 0xd2, 0x50, 0xd6, 0x09, 0x52, 0x4f,
	0xd1, 0x12, 0x4f, 0x53, 0x8b, 0x24, 0x4e, 0xbc, 0x0e, 0x12, 0x6f, 0xc0, 0x89, 0xa7, 0xe1, 0x2d,
	0x78, 0x29, 0xb4, 0x3f, 0x0e, 0x81, 0xc2, 0x81, 0x93, 0x67, 0xbe, 0xf9, 0x76, 0xbe, 0xd9, 0xd9,
	0xcf, 0x00, 0x5b, 0x41, 0x45, 0x67, 0x5d, 0xe4, 0x65, 0x8e, 0x8e, 0x8c, 0xc3, 0x17, 0xe0, 0x8c,
	0xf8, 0x92, 0xf0, 0x01, 0xb8, 0x37, 0x59, 0x21, 0xca, 0xc0, 0x6a, 0x59, 0xe7, 0x75, 0xa6, 0x13,
	0x44, 0x70, 0x16, 0x5c, 0x94, 0x81, 0xad, 0x40, 0x15, 0x87, 0xdf, 0x2c, 0x70, 0x26, 0x82, 0x0a,
	0x3c, 0x01, 0x3b, 0x4b, 0x0d, 0xdf, 0xce, 0x52, 0xf4, 0xa1, 0xc6, 0xe7, 0xa4, 0xb8, 0x2e, 0x93,
	0x21, 0x3e, 0x06, 0x67, 0xc5, 0x97, 0x14, 0xd4, 0x5a, 0xd6, 0x79, 0xa3, 0x0b, 0x1d, 0xa5, 0x2e,
	0xe5, 0x98, 0xc2, 0xa5, 0x28, 0x2d, 0x79, 0xb6, 0x08, 0x1c, 0x2d, 0xaa, 0x12, 0x89, 0xae, 0x6f,
	0xf3, 0x15, 0x05, 0xae, 0x46, 0x55, 0x82, 0x01, 0x1c, 0xf0, 0x34, 0x2d, 0x48, 0x88, 0xc0, 0x53,
	0x78, 0x95, 0x86, 0x75, 0x38, 0x18, 0x66, 0xa2, 0x64, 0xb4, 0x09, 0xdb, 0x50, 0xef, 0x15, 0xc4,
	0x4b, 0x62, 0xb4, 0x91, 0xea, 0x52, 0x50, 0x4d, 0xb8, 0x53, 0x97, 0x93, 0x33, 0x7d, 0x75, 0x06,
	0x50, 0x91, 0xc5, 0x1a, 0x9f, 0x82, 0x27, 0x4a, 0x5e, 0x6e, 0x85, 0xe1, 0x1f, 0x69, 0x7e, 0xa2,
	0x30, 0x66, 0x6a, 0xbb, 0x9e, 0xf6, 0x3f, 0x7a, 0x7e, 0xb5, 0xe0, 0x28, 0x21, 0x5e, 0xcc, 0x6e,
	0xa3, 0xb9, 0x1a, 0xe2, 0x15, 0x1c, 0xf2, 0x39, 0x31, 0xbe, 0x9a, 0x93, 0x69, 0xfc, 0xc8, 0x34,
	0xde, 0x63, 0x75, 0x22, 0x43, 0x61, 0x3b, 0xf2, 0xd9, 0x6b, 0x38, 0xac, 0x50, 0xf9, 0x0c, 0x37,
	0x45, 0xbe, 0x54, 0x0d, 0x5c, 0xa6, 0x62, 0x7c, 0x02, 0x8d, 0x32, 0x9f, 0x66, 0xab, 0xd9, 0x62,
	0x9b, 0x52, 0x6a, 0xb6, 0x0e, 0x65, 0x1e, 0x1b, 0x24, 0x7c, 0x06, 0xc7, 0x5a, 0x43, 0x2d, 0x9c,
	0x36, 0x72, 0xaf, 0x9b, 0x2d, 0x15, 0x5f, 0xaa, 0x27, 0x56, 0x49, 0x38, 0x06, 0xd0, 0xb4, 0xff,
	0xd8, 0x42, 0x0b, 0x5c, 0x09, 0x8b, 0xc0, 0x6e, 0xd5, 0xfe, 0x58, 0x83, 0x2e, 0x84, 0xdf, 0x2d,
	0xf0, 0xf4, 0x21, 0x6c, 0x83, 0x33, 0xcb, 0x53, 0x7d, 0xfb, 0x93, 0xee, 0xc3, 0xfd, 0x86, 0xe6,
	0xd3, 0xcb, 0x53, 0x62, 0x8a, 0x24, 0x3d, 0xb4, 0x14, 0x73, 0xe3, 0x37, 0x19, 0x86, 0x9f, 0x00,
	0x7e, 0xb1, 0x10, 0xc0, 0x7b, 0x13, 0xc5, 0xc3, 0x41, 0xdf, 0xbf, 0x87, 0x4d, 0x68, 0x8c, 0xde,
	0x4d, 0xe3, 0xcb, 0xab, 0xe1, 0xf4, 0x7a, 0x30, 0xf6, 0x2d, 0xbc, 0x0f, 0xc7, 0xf1, 0xe8, 0x43,
	0x34, 0x8c, 0xfb, 0xd3, 0xf7, 0x93, 0x01, 0xbb, 0xf6, 0x6d, 0x3c, 0x85, 0xe6, 0x55, 0xc4, 0xc6,
	0x71, 0x34, 0x9c, 0x26, 0x93, 0x5e, 0x6f, 0x90, 0x24, 0x7e, 0x0d, 0x1b, 0x70, 0x50, 0x25, 0x8e,
	0x4c, 0xd8, 0x20, 0xea, 0x5f, 0x26, 0x6f, 0x7d, 0xb7, 0xfb, 0xc3, 0x82, 0x86, 0xbc, 0x46, 0x42,
	0xc5, 0xe7, 0x6c, 0x46, 0xd8, 0x06, 0x4f, 0x5b, 0x04, 0x9b, 0x7a, 0xee, 0x9d, 0xbb, 0xce, 0xfc,
	0xdf, 0x01, 0xb1, 0xc6, 0xe7, 0xe0, 0x48, 0x1f, 0xe2, 0xb1, 0xae, 0x18, 0x4f, 0x56, 0xc4, 0xbd,
	0x25, 0x5f, 0x54, 0x2b, 0x57, 0x7f, 0xde, 0xe9, 0x7e, 0xdd, 0xbc, 0xd5, 0x5f, 0x0e, 0xbd, 0x84,
	0xfa, 0xce, 0x32, 0x88, 0x77, 0x3d, 0x74, 0xf7, 0xc8, 0x47, 0x4f, 0xfd, 0xe8, 0x17, 0x3f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0x2f, 0x80, 0x73, 0xf6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*SearchResp, error)
	// Searches in a fuzzy-way.
	SearchName(ctx context.Context, in *SearchNameReq, opts ...grpc.CallOption) (*SearchResp, error)
	SearchAge(ctx context.Context, in *SearchAgeReq, opts ...grpc.CallOption) (*SearchResp, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, "/user.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*SearchResp, error) {
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, "/user.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchName(ctx context.Context, in *SearchNameReq, opts ...grpc.CallOption) (*SearchResp, error) {
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, "/user.UserService/SearchName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchAge(ctx context.Context, in *SearchAgeReq, opts ...grpc.CallOption) (*SearchResp, error) {
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, "/user.UserService/SearchAge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateReq) (*CreateResp, error)
	List(context.Context, *ListReq) (*SearchResp, error)
	// Searches in a fuzzy-way.
	SearchName(context.Context, *SearchNameReq) (*SearchResp, error)
	SearchAge(context.Context, *SearchAgeReq) (*SearchResp, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SearchName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchName(ctx, req.(*SearchNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SearchAge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchAge(ctx, req.(*SearchAgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
		{
			MethodName: "SearchName",
			Handler:    _UserService_SearchName_Handler,
		},
		{
			MethodName: "SearchAge",
			Handler:    _UserService_SearchAge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
